name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Update submodules
        run: git submodule update --init --recursive  
        
      - name: Install vcpkg
        run: |
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg integrate install
          
      - name: Install vcpkg dependencies
        run: vcpkg install --feature-flags=manifests --allow-unsupported
