name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg dependencies
        run: |
          vcpkg_directory="$GITHUB_WORKSPACE/LancelotEngine/vcpkg"
          vcpkg_args="--overlay-ports=$GITHUB_WORKSPACE"
          vcpkg_with_tests="OFF"

          echo "::group::Setup and install vcpkg dependencies"
          git -C "$vcpkg_directory" submodule update --init vcpkg
          echo "$vcpkg_args" > "$vcpkg_directory/vcpkg_args.file"
          touch "$vcpkg_directory/main.cpp"
          mkdir -p "$vcpkg_directory/build"

          cmake "$vcpkg_directory" -DCMAKE_BUILD_TYPE=Release -S "$vcpkg_directory" -B "$vcpkg_directory/build"
          cmake --build "$vcpkg_directory/build" --target install --config Release --parallel

          echo "::endgroup::"

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . 
