name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup vcpkg dependencies
        run: |
          vcpkg_directory="$GITHUB_WORKSPACE/vcpkg"
          vcpkg_args="--overlay-ports=$GITHUB_WORKSPACE"
          vcpkg_with_tests="OFF"      
          git -C "$vcpkg_directory" submodule update --init vcpkg
          cmake -S "$GITHUB_WORKSPACE" -B "$vcpkg_directory/build" "-DCMAKE_TOOLCHAIN_FILE=$vcpkg_directory/scripts/buildsystems/vcpkg.cmake"
          cmake --build "$vcpkg_directory/build" --target install --config Release --parallel
      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
